const navItems=document.querySelectorAll('.nav-item'),views=document.querySelectorAll('.view'),pageTitle=document.getElementById('page-title'),sidebarToggle=document.getElementById('sidebar-toggle');
navItems.forEach(item=>item.addEventListener('click',()=>{const target=document.getElementById(item.dataset.view);if(!target)return;navItems.forEach(x=>x.classList.remove('active'));views.forEach(x=>x.classList.remove('active'));item.classList.add('active');target.classList.add('active');pageTitle.textContent=item.childNodes[2]?.textContent?.trim()||item.textContent.trim();sidebarToggle.checked=false;window.scrollTo({top:0,behavior:'smooth'});}));

const batchesView=document.getElementById('batches');batchesView?.querySelector('.empty-demo')?.remove();
let records=[{id:1,type:'Training',subject:'Microsoft Office',batch:'Office B-08',days:'Sat, Mon, Wed',time:'10:00–11:30 AM',mode:'Offline',place:'Lab 01',teacher:'Md. Faruk'},{id:2,type:'Coaching',subject:'Class 10 Physics',batch:'Science S-04',days:'Sun, Tue, Thu',time:'03:00–04:30 PM',mode:'Offline',place:'Room 03',teacher:'S. Rahman'},{id:3,type:'Training',subject:'IELTS Reading',batch:'IELTS E-03',days:'Sun, Tue',time:'07:00–08:30 PM',mode:'Online',place:'Google Meet',teacher:'Sadia Rahman'}];
batchesView?.insertAdjacentHTML('beforeend',`<div class="batch-manager"><form class="batch-form" id="batch-form"><h3>Subject / Training Batch / Time Slot</h3><input type="hidden" id="record-id"><label>Program type<select id="batch-type"><option>Training</option><option>Coaching</option></select></label><label>Subject / Course<input id="batch-subject" required placeholder="Microsoft Office"></label><label>Batch name<input id="batch-name" required placeholder="Office B-09"></label><div class="form-row"><label>Class days<input id="batch-days" required placeholder="Sat, Mon, Wed"></label><label>Time slot<input id="batch-time" required placeholder="10:00–11:30"></label></div><div class="form-row"><label>Mode<select id="batch-mode"><option>Offline</option><option>Online</option></select></label><label>Room / Link<input id="batch-place" required placeholder="Lab 01"></label></div><label>Teacher<input id="batch-teacher" required placeholder="Teacher name"></label><button class="primary-button" type="submit">Save batch & slot</button></form><div class="batch-table"><table><thead><tr><th>Subject/Course</th><th>Batch</th><th>Days & Time</th><th>Mode</th><th>Teacher</th><th>Actions</th></tr></thead><tbody id="batch-rows"></tbody></table></div></div>`);
const f=id=>document.getElementById(id),form=f('batch-form'),rows=f('batch-rows');
function render(){if(!rows)return;rows.innerHTML=records.map(r=>`<tr><td><b>${r.subject}</b><br><small>${r.type}</small></td><td>${r.batch}</td><td>${r.days}<br><small>${r.time}</small></td><td><span class="status ${r.mode.toLowerCase()}">${r.mode}</span><br><small>${r.place}</small></td><td>${r.teacher}</td><td><div class="crud-actions"><button data-edit="${r.id}">Edit</button><button class="delete" data-delete="${r.id}">Delete</button></div></td></tr>`).join('');}
form?.addEventListener('submit',e=>{e.preventDefault();const id=Number(f('record-id').value),r={id:id||Date.now(),type:f('batch-type').value,subject:f('batch-subject').value,batch:f('batch-name').value,days:f('batch-days').value,time:f('batch-time').value,mode:f('batch-mode').value,place:f('batch-place').value,teacher:f('batch-teacher').value};records=id?records.map(x=>x.id===id?r:x):[...records,r];form.reset();f('record-id').value='';render();});
rows?.addEventListener('click',e=>{const edit=Number(e.target.dataset.edit),del=Number(e.target.dataset.delete);if(del){records=records.filter(r=>r.id!==del);render();}if(edit){const r=records.find(x=>x.id===edit);if(!r)return;f('record-id').value=r.id;f('batch-type').value=r.type;f('batch-subject').value=r.subject;f('batch-name').value=r.batch;f('batch-days').value=r.days;f('batch-time').value=r.time;f('batch-mode').value=r.mode;f('batch-place').value=r.place;f('batch-teacher').value=r.teacher;}});render();
const tr=new Map([['ড্যাশবোর্ড','Dashboard'],['আয় ও ব্যয়','Collections & Expenses'],['কোর্সসমূহ','Courses'],['ব্যাচ ও ক্লাস','Batches & Classes'],['শিক্ষার্থী','Students'],['ফ্রি ভিডিও','Free Videos'],['ভর্তি অনুসন্ধান','Admission Enquiries'],['নোটিশ','Notices'],['সেটিংস','Settings'],['আয় ও ব্যয়ের হিসাব','Collections & Expenses'],['মোট আদায়','Total Collections'],['মোট ব্যয়','Total Expenses'],['নিট ব্যালেন্স','Net Balance'],['বকেয়া','Outstanding Fees'],['আগস্ট বনাম জুলাই','August vs July'],['মাসিক তুলনামূলক রিপোর্ট','Monthly Comparison Report'],['পার্থক্যের কারণ','Reasons for Change'],['আজকের ক্লাস','Today’s Classes'],['সাম্প্রতিক কার্যক্রম','Recent Activity'],['সাম্প্রতিক ভর্তি','Recent Admissions'],['ওয়েবসাইট দেখুন ↗','View Website ↗']]),rev=new Map([...tr].map(([a,b])=>[b,a]));let lang='bn';
function translate(map){const w=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT),n=[];while(w.nextNode())n.push(w.currentNode);n.forEach(x=>{const raw=x.nodeValue,c=raw.trim();if(map.has(c))x.nodeValue=raw.replace(c,map.get(c));});}f('language-toggle')?.addEventListener('click',e=>{const en=lang==='bn';translate(en?tr:rev);lang=en?'en':'bn';document.documentElement.lang=lang;e.currentTarget.textContent=en?'বাংলা':'EN';});
